# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 企鹅读书node

on:
    workflow_dispatch:
    schedule:
      - cron: "*/5 * * * *"
    watch:
      types: [started]
    repository_dispatch:
      types: qqreadnode

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: Lexho1/Lexho
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        run: |
          npm install
      - name: '运行 【企鹅读书】node'
        run: |
          node Task/box.js
        env:
          QQREAD_BODY: ${{ secrets.QQREAD_BODY }}
          QQREAD_TIMEURL: ${{ secrets.QQREAD_TIMEURL }}
          QQREAD_TIMEHD: ${{ secrets.QQREAD_TIMEHD }}
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}
          BARK_SOUND: ${{ secrets.BARK_SOUND }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
          DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
          DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}