name: 企鹅

on:
    workflow_dispatch:
    #schedule:
      #- cron: "*/30 * * * *"
    watch:
      types: [started]
    repository_dispatch:
      types: qqreads

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        run: |
          npm install
      - name: '运行 【rl】'
        run: |
          node Task/qqreads.js
        env:
          QQREAD_BODY: ${{ secrets.QQREAD_BODY }}
          QQREAD_TIMEURL: ${{ secrets.QQREAD_TIMEURL }}
          QQREAD_TIMEHD: ${{ secrets.QQREAD_TIMEHD }}
          QQREAD_CASH: ${{ secrets.QQREAD_CASH }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}