# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 书旗@ziye2

on:
    workflow_dispatch:
    #schedule:
      #- cron: "0 */1 * * *"
    watch:
      types: [started]
    repository_dispatch:
      types: shuqi

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: '运行 【shuqi】'
        run: |
          node sqxs/shuqi.ziye-2.js
        env:
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}