# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: sqxs2

on:
    workflow_dispatch:
    schedule:
      - cron: "0 0,8 * * *"
    watch:
      types: [started]
    repository_dispatch:
      types: sq

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: npm install
        run: |
          npm install
          npm install cron
          npm install request
          curl ipinfo.io/json
      - name: '运行 【sqxs】'
        run: |
          node sqxs/g2/sqxs2.js