name: 书旗&羊毛赚
on:
  workflow_dispatch:
  schedule:
    - cron: '0 21 * * *'
jobs:
  build:
    runs-on: ubuntu-latest       
    steps:
      
      - name: Checkout
        run: |
          git clone https://github.com/tsuyoshi727/Action.git ~/Action
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: npm install
        run: |
          cd ~/Action
          npm install
          npm install cron
          npm install request
          curl ipinfo.io/json

      - name: '【书旗小说】'
        run: |
          cd ~/Action   
          node sqxs/sqxs.js