name: 书旗

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0,7 * * *'
jobs:
  build:
    runs-on: ubuntu-latest       
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/tsuyoshi727/Action.git ~/sqxs
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: npm install
        run: |
          cd ~/sqxs
          npm install
          npm install cron
          npm install request
          curl ipinfo.io/json
      - name: '运行 【youthshare】'
        run: |
          cd ~/sqxs   
          node sqxs/sqxs.js
