name: 中青阅读2

on:
  workflow_dispatch:
  schedule:
     - cron: '0 0-14/3 * * *'
jobs:
  build:
    runs-on: ubuntu-latest    
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/tsuyoshi727/Action.git ~/Action
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: npm install
        run: |
          cd ~/Action
          npm install
          npm install cron
          npm install request
      - name: '运行 【中青阅读1】'
        run: |
          cd ~/Action
          node youth/liv.youthread.js
