name: zqshare3

on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 6-10 * * *'
jobs:
  build:
    runs-on: ubuntu-latest       
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/tsuyoshi727/Action.git ~/Task
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: npm install
        run: |
          cd ~/Task
          npm install
          npm install cron
          npm install request
          npm install md5-node
      - name: '运行 【youthshare】'
        run: |
          cd ~/Task   
          node Task/youthshare3.js
